// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build wasip2

package monotonicclock

// This file contains wasmimport and wasmexport declarations for "wasi:clocks@0.2.7".

//go:wasmimport wasi:clocks/monotonic-clock@0.2.7 now
//go:noescape
func wasmimport_Now() (result0 uint64)

//go:wasmimport wasi:clocks/monotonic-clock@0.2.7 resolution
//go:noescape
func wasmimport_Resolution() (result0 uint64)

//go:wasmimport wasi:clocks/monotonic-clock@0.2.7 subscribe-instant
//go:noescape
func wasmimport_SubscribeInstant(when0 uint64) (result0 uint32)

//go:wasmimport wasi:clocks/monotonic-clock@0.2.7 subscribe-duration
//go:noescape
func wasmimport_SubscribeDuration(when0 uint64) (result0 uint32)
