// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build wasip2

package timezone

// This file contains wasmimport and wasmexport declarations for "wasi:clocks@0.2.4".

//go:wasmimport wasi:clocks/timezone@0.2.4 display
//go:noescape
func wasmimport_Display(when0 uint64, when1 uint32, result *TimezoneDisplay)

//go:wasmimport wasi:clocks/timezone@0.2.4 utc-offset
//go:noescape
func wasmimport_UtcOffset(when0 uint64, when1 uint32) (result0 uint32)
