// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build wasip2

package wallclock

// This file contains wasmimport and wasmexport declarations for "wasi:clocks@0.2.7".

//go:wasmimport wasi:clocks/wall-clock@0.2.7 now
//go:noescape
func wasmimport_Now(result *DateTime)

//go:wasmimport wasi:clocks/wall-clock@0.2.7 resolution
//go:noescape
func wasmimport_Resolution(result *DateTime)
